# -*- coding: utf-8 -*-
"""Copy of project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IaE6F4Cbmd5XLM77PCC7S8kBxpQ5I4XB
"""

import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files
uploaded=files.upload()

alloc_df = pd.read_csv("alloc.csv")

remove_time = alloc_df[alloc_df["type"] == "time"].index
remove_time

alloc_subset = alloc_df.drop(remove_time)
alloc_subset

alloc_movies = alloc_subset[
    ["time", "ls_int", "ls_long", "cached", "puts"]
]
alloc_movies

remove_puts_movie = alloc_movies[alloc_movies["puts"] >= 98].index
remove_puts_movie

plt.plot(alloc_movies["ls_long"], alloc_movies["ls_int"])

plt.xlabel("ls_long")
plt.ylabel("ls_int")

plt.show()

plt.subplot(1, 2, 1)
plt.plot(alloc_movies["puts"], alloc_movies["time"])
plt.title("DURATION")

#plot 2:


plt.subplot(1, 2, 2)
plt.plot(alloc_movies["puts"], alloc_movies["time"])
plt.title("puts")

plt.suptitle("ls_int vs ls_int")
plt.show()

#Create a subplot with 2 rows and 2 columns


plt.subplot(3, 2, 1)
plt.plot(alloc_movies["puts"], alloc_movies["time"])
plt.title("time")


plt.subplot(3, 2, 2)
plt.plot(alloc_movies["puts"], alloc_movies["time"])
plt.title("puts")


plt.subplot(3, 2, 5)
plt.plot(alloc_movies["puts"], alloc_movies["time"])
plt.title("ls_long")


plt.subplot(3, 2, 6)
plt.plot(alloc_movies["puts"], alloc_movies["time"])
plt.title("ls_int")


plt.show()